# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build & test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Restore cache
      id: restore-gradle-cache
      uses: actions/cache@v2.1.1
      with:
        path: |
          ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-{{ hashFiles('**/*.gradle*') }}
    - name: Install dependencies
      if: steps.restore-gradle-cache.outputs.cache-hit != 'true'
      run: ./gradlew dependencies
    - name: Build with Gradle
      run: ./gradlew build
